name: Dockerize

on:
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  BLOCK_REGISTRY: ${{ secrets.BLOCK_REGISTRY }}

jobs:
   dockerize_block:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v2

       - name: Get the version
         id: get_version
         run: |
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
            SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
            echo ::set-output name=BRANCH::${BRANCH}
            echo ::set-output name=VERSION::${BRANCH}-${SHORT_SHA}     

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build zblock
         run: |
            docker build -t $BLOCK_REGISTRY:$TAG -f "$DOCKERFILE_BLOCK" .
            docker tag $BLOCK_REGISTRY:$TAG $BLOCK_REGISTRY:latest
            docker push $BLOCK_REGISTRY:$TAG
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_BLOCK: "docker.local/Dockerfile"

       - name: Push image
         run: |
           if [[ "$PUSH_LATEST" == "yes" ]]; then
             docker push $BLOCK_REGISTRY:latest
           else
             docker push $BLOCK_REGISTRY:$TAG
           fi
         env:
           PUSH_LATEST: ${{ github.event.inputs.latest_tag }}
           TAG: ${{ steps.get_version.outputs.VERSION }}
